### PR TITLE
Swift 4

### PR DESCRIPTION
**Pull request by pdupris**
### Description of the Changes

Updated to support Swift 4 and Xcode 9. 

Did not update pod version - i'll leave this to the Kaltura team

### CheckLists

- [X] changes have been done against master branch, and PR does not conflict
- [NA] new unit / functional tests have been added (whenever applicable)
- [X] test are passing in local environment 
- [ ] Travis tests are passing (or test results are not worse than on master branch :))
- [NA] Docs have been updated

### CODE REVIEW

**Comment by kaltura-hooks** [comment]
Hi @pdupris,
Thank you for contributing this pull request!
Please sign the Kaltura CLA so we can review and merge your contribution.
Learn more at http://bit.ly/KalturaContrib

**Comment by ElizaSapir** [comment]
Hey @pdupris,

Thanks for your PR.

* Please make sure Travis get a green light by fixing the following issue on your PR:

```ruby
Check dependencies
“Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.
“Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.
```

* Don't forget to sign CLA, then we will approve your PR.

Thanks,

Eliza

**Comment by ElizaSapir** [comment]
@pdupris  hey, please close this PR and open new one based in develop (not master).

Thanks!

**Comment by ElizaSapir** [comment]
Hey @pdupris,

Thank you for contributing this pull request!
* Since we have a lot of repos that are dependent with this repo (PlayKit-Core) we have to add additional fixes.
* All PRs must be open in front of Develop.

We are going to close this repo and manage swift4 support on: https://github.com/kaltura/playkit-ios/pull/232 please follow and add attachments or any feedback you wish.

Thanks!!!

**Pull request closed without merging**
