### PR TITLE
Make PhoenixMediaProvider.createMediaEntry function static and public

### PR DESCRIPTION
**Pull request by vadimkononov**
This allows the application to call it.

### CODE REVIEW

**Comment by gal-orlanczyk** [comment]
@vadimkononov, can you give me a bit more information about this change?

**Comment by ElizaSapir** [comment]
@gal-orlanczyk let's resolve conflicts and make sure to merge this PR

**Comment by ElizaSapir** [comment]
@gal-orlanczyk let's resolve conflicts and make sure to merge this PR

**Comment by ElizaSapir** [comment]
@vadimkononov  please resolve conflict and merge the PR.
Thanks!

**Pull request merged**
