### PR TITLE
expose public player

### PR DESCRIPTION
**Pull request by matteocrippa**
### Description of the Changes

Expose the `player` as public in `PlayerView.swift`, keeping as internal doesn't allow to use it.

### CheckLists

- [ ] changes have been done against master branch, and PR does not conflict
- [ ] new unit / functional tests have been added (whenever applicable)
- [ ] test are passing in local environment 
- [ ] Travis tests are passing (or test results are not worse than on master branch :))
- [ ] Docs have been updated

### CODE REVIEW

**Comment by matteocrippa** [comment]
Check list above is not applicable, `master` branch is not more the reference, I see you moved to develop.
The rest is out of scope for this PR.

**Comment by kaltura-hooks** [comment]
Hi @matteocrippa,
Thank you for contributing this pull request!
Please sign the Kaltura CLA so we can review and merge your contribution.
Learn more at http://bit.ly/KalturaContrib

**Comment by x-NR-x** [comment]
Hi @matteocrippa,

Thank you for contacting us.
If I can ask, why do you need it exposed?
This was done on purpose.

Thanks,
Nilit Danan

**Comment by matteocrippa** [comment]
Scope is to have the lean approach to implement the player as close as the native solution, I noticed that doing something like

```swift
let player = PlayKitManager.shared.loadPlayer()
let playerView = PlayerView()
let controller = AVPlayerController()
controller.player = player.view?.player
```

is not possibile because `player` visibility is `internal`

**Comment by x-NR-x** [comment]
Hi @matteocrippa,

Even if our player will be accessible, you won't be able to do that cause our player is not an AVPlayer instance.
Our engine is mainly AVPlayer, but not for VR content.

**Comment by matteocrippa** [comment]
Got it, but considering that I don't need any VR and I don't want to write from scratch the UI of the video player provide, having direct access to the AVPlayer instance is fair enough for the most basic flow of use a video player streaming

**Comment by x-NR-x** [comment]
I understand you, and we are working on a UI solution.
If you would like I can send you something to start you up from.

**Comment by matteocrippa** [comment]
if you want you can, but to be honest for my casual implementation need is fine that solution to have the player exposed to be public.

**Pull request closed without merging**
