### PR TITLE
FEM-1688: playkit swift 4 support

### PR DESCRIPTION
**Pull request by vadimkononov**
### Description of the Changes

Please add a detailed description of the change, weather it's an enhancement or a bugfix.
If the PR is related to an open issue please link to it.

### CheckLists

- [x] changes have been done against master branch, and PR does not conflict
- [ ] new unit / functional tests have been added (whenever applicable)
- [x] test are passing in local environment 
- [x] Travis tests are passing (or test results are not worse than on master branch :))
- [ ] Docs have been updated

### CODE REVIEW

**Comment by ElizaSapir** [comment]
@vadimkononov  let's make sure we update docs by removing the swift version line on samples podfile + https://github.com/kaltura/DeveloperPortalDocs/blob/master/documentation/Mobile-Video-Player-SDKs/v3_iOS_QuickStart.md

Thanks!

cc @OrenMe

**Comment by ElizaSapir** [comment]
test this please

**Comment by noamtamim** [comment]
Jenkins:rebuild

**Comment by harrisrap** [comment]
I'm trying to update to this new version 3.3.0, https://github.com/kaltura/playkit-ios/releases/tag/v3.3.0, but apparently it's still just in the "develop" branch, so I'm getting this error when I run "pod install"

None of your spec sources contain a spec satisfying the dependency: `PlayKit (~> 3.3.0)`.

**Pull request merged**
