### PR TITLE
Exposed uri in PKPlaybackInfo

### PR DESCRIPTION
**Pull request by naveen-c**
### Description of the Changes

This is an enhancement to add playback item URI to the standard PlayKit Playback Info.

### CheckLists

- [x] changes have been done against master branch, and PR does not conflict
- [x] new unit / functional tests have been added (whenever applicable)
- [x] test are passing in local environment 
- [x] Travis tests are passing (or test results are not worse than on master branch :))
- [x] Docs have been updated

### CODE REVIEW

**Comment by kaltura-hooks** [comment]
Hi @naveen-c,
Thank you for contributing this pull request!
Please sign the Kaltura CLA so we can review and merge your contribution.
Learn more at http://bit.ly/KalturaContrib

**Comment by OrenMe** [comment]
@naveen-c the URI is the playback URI you set for the asset, what is the use case for it? don;t you already have it?

**Comment by naveen-c** [comment]
@OrenMe In the case of HLS video, the URI in AVPlayerItemAccessLogEvent represents the URI of the currently selected HLS stream (entries in .m3u8 file). 
I could not find that information in any place other than AVPlayerItemAccessLogEvent.
We need this information to track which quality stream is being played.

**Comment by OrenMe** [comment]
Got it, thanks.
For this we expose the indicatedBitrate so you can know exactly which rendition is being played.

**Comment by OrenMe** [comment]
We also expose this as a track change event so analytics can track this data: https://github.com/kaltura/playkit-ios/blob/89a7c7f9bb2d737fda18dfb5f101f87713a5bd9f/Classes/Player/AVPlayerEngine/AVPlayerEngine%2BObservation.swift#L81

**Comment by naveen-c** [comment]
Got it.
So maybe we should expose this URI field in VideoTrackChanged event so that the consumer doesn't need to parse the .m3u8 file to get the URI from indicatedBitrate

**Comment by naveen-c** [comment]
@OrenMe shall I go ahead and make these changes in VideoTrackChanged event?

**Comment by OrenMe** [comment]
Thanks @naveen-c , please let us check as the model needs to fit between various SDKs we expose and it is usually not common to identify a stream by its url also in ends that support this.
What do you do in web and android? We do not expose the urls there as well.

**Comment by x-NR-x** [comment]
Hi @naveen-c,

Did you have the time to check what is done on your side for the Web and Android implementation for this case?

Thanks,
Nilit

**Comment by naveen-c** [comment]
@OrenMe , @x-NR-x sorry for the delay in response.
On Android, we are using DASH files (.mpd) and consume [onDecoderInputFormatChanged](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/analytics/AnalyticsListener.html#onDecoderInputFormatChanged-com.google.android.exoplayer2.analytics.AnalyticsListener.EventTime-int-com.google.android.exoplayer2.Format-) event of Exoplayer, which has information of the selected track id

**Comment by OrenMe** [comment]
@naveen-c are you patching your copy of playkit-android to get this? or using the profiler interface?

**Comment by naveen-c** [comment]
On Android we are using exoplayer directly, and not kaltura's sdk

**Comment by OrenMe** [comment]
Thanks @naveen-c, as we need to have compatibility in data model across SDKs we first will need to standardise this across them.
I do not have a date for this, but thank you for raising this so we know this data is required.
In general I would recommend building on the video metadata like bitrates and resolution and not necessarily urls.

**Comment by naveen-c** [comment]
@OrenMe thanks for the update. For some reason, bitrate is not enough for our analytics. 
As you mentioned resolution, is that information exposed in the SDK?

Also, until you make a decision on standardizing the data across SDKs and expose the requested data, is it fine if I use my fork of the repository in my project?

**Comment by OrenMe** [comment]
Hi @naveen-c , so resolution data will solve your issue? Is that the important info for your case?
And in general you can use your fork, but it will require you to sync the upstream every new release.
Is this for FK project? You mentioned you are not using the android sdk as well, any reason not to but yes for iOS?

**Comment by naveen-c** [comment]
@OrenMe I think resolution can help, I will check with the team on this.

So the FK project has multiple sub-projects in itself, and on Android, we are using Kaltura SDK for some parts, and Exoplayer directly in older flows. 
While on iOS we have recently taken a decision to use this SDK in legacy flows as well.

**Pull request closed without merging**
